In [11]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("tongpython/cat-and-dog")

print("Path to dataset files:", path)

Path to dataset files: /root/.cache/kagglehub/datasets/tongpython/cat-and-dog/versions/1


In [12]:
import os
import cv2
import numpy as np
cat_data = [];
for filenames in os.walk(path + '/training_set/training_set/cats/'):
  for cats in filenames:
    for cat in cats:
        img = cv2.imread(path + '/training_set/training_set/cats/' + cat)
        if img is not None:
          img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
          img = cv2.resize(img, (100,100))
          img = np.expand_dims(img, axis=-1)
          img = img / 255.0
          cat_data.append(img)

dog_data = [];
for filenames in os.walk(path + '/training_set/training_set/dogs/'):
  for dogs in filenames:
    for dog in dogs:
        img = cv2.imread(path + '/training_set/training_set/dogs/' + dog)
        if img is not None:
          img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
          img = cv2.resize(img, (100,100))
          img = np.expand_dims(img, axis=-1)
          img = img / 255.0
          dog_data.append(img)

print('test cat :' + str(len(cat_data)))
print('test dog :' + str(len(dog_data)))

test cat :4000
test dog :4005


In [13]:


import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, Input

def create_model():
    model = Sequential()
    # First convolutional layer
    model.add(Conv2D(16, (6, 6), activation='relu', input_shape=(100, 100, 1)))
    model.add(MaxPooling2D(pool_size=(2, 2)))  # Pooling layer to reduce spatial dimensions

    # Second convolutional layer
    model.add(Conv2D(32, (6, 6), activation='relu', padding='same'))
    model.add(MaxPooling2D(pool_size=(2, 2)))  # Pooling layer to reduce spatial dimensions

    model.add(Flatten())  # Flatten the output for the Dense layer
    model.add(Dense(100, activation='relu'))  # Fully connected layer
    model.add(Dropout(0.5))
    model.add(Dense(1, activation='sigmoid'))  # Output layer for binary classification

    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

In [14]:
y_cat = np.zeros(len(cat_data))
y_dog = np.ones(len(dog_data))

X_train = np.concatenate((cat_data, dog_data), axis=0)  # Shape: (num_samples, 32, 32, 1)
y_train = np.concatenate((y_cat, y_dog), axis=0)  # Shape: (num_samples,)

# Shuffle the dataset and labels
indices = np.arange(X_train.shape[0])  # Create an array of indices
print(indices)
np.random.shuffle(indices)  # Shuffle the indices
print(indices)
# Use the shuffled indices to shuffle the data and labels
X_train = X_train[indices]
y_train = y_train[indices]
print(y_train)

[   0    1    2 ... 8002 8003 8004]
[5142  444  940 ... 1008 2321 2130]
[1. 0. 0. ... 0. 0. 0.]


In [15]:
cat_or_dog = create_model()
cat_or_dog.fit(X_train, y_train, epochs=15)
cat_or_dog.save('cat_or_dog.h5')

Epoch 1/15
251/251 ━━━━━━━━━━━━━━━━━━━━ 7s 15ms/step - accuracy: 0.5216 - loss: 0.7099
Epoch 2/15
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.6225 - loss: 0.6561
Epoch 3/15
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.6787 - loss: 0.6012
Epoch 4/15
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.7561 - loss: 0.5154
Epoch 5/15
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8075 - loss: 0.4289
Epoch 6/15
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8341 - loss: 0.3785
Epoch 7/15
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.8881 - loss: 0.2802
Epoch 8/15
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9139 - loss: 0.2231
Epoch 9/15
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9416 - loss: 0.1552
Epoch 10/15
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9577 - loss: 0.1173
Epoch 11/15
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9660 - loss: 0.1003
Epoch 12/15
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/ste

In [16]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("samuelcortinhas/cats-and-dogs-image-classification")

print("Path to dataset files:", path)

import os
import cv2
import numpy as np
test_cat = [];
for filenames in os.walk(path + '/train/cats/'):
    for file in filenames:
      for cat in file:
        img = cv2.imread(path + '/train/cats/' + cat)
        if img is not None:
          img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
          img = cv2.resize(img, (100,100))
          img = np.expand_dims(img, axis=-1)
          img = img / 255.0
          test_cat.append(img)

test_dog = [];
for filenames in os.walk(path + '/train/dogs/'):
    for file in filenames:
      for dog in file:
        img = cv2.imread(path + '/train/dogs/' + dog)
        if img is not None:
          img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
          img = cv2.resize(img,( 100,100))
          img = np.expand_dims(img, axis=-1)
          img = img / 255.0
          test_dog.append(img)

100%|██████████| 64.4M/64.4M [00:00<00:00, 91.6MB/s]

Extracting files...


Path to dataset files: /root/.cache/kagglehub/datasets/samuelcortinhas/cats-and-dogs-image-classification/versions/4


In [41]:
predictions = cat_or_dog.predict(test_dog[1].reshape(1, 100, 100, 1))
if(predictions[0]*100 > 50):
  print('dog')
else:
  print('cat')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
dog
